---
title: "Visualization"
author: "Hongtong Lin"
date: "2026-10-01"
output: github_document
---

loading libraries
```{r, message = FALSE}
library(tidyverse)
library(ggridges)

library(p8105.datasets)
data("weather_df")
```
  

```{r}
dim(weather_df)
str(weather_df)
head(weather_df)
colnames(weather_df)
```
  
Let's make some scatterplots  

```{r}
ggplot(weather_df, aes(x = tmin, y=tmax)) +
  geom_point()
```


do the data frame first
```{r}
gg_temp_scatterplot <-
  weather_df |> 
    ggplot(aes(x = tmin, y=tmax)) +
    geom_point()

gg_temp_scatterplot
```



make it a bit fancier

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y=tmax, color = name)) +
  geom_point(alpha = .25) +
  geom_smooth(se=FALSE)

```

Show faceting  

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.5) +
  facet_grid(. ~name) # rows ~ columns, and the period is a placeholder meaning "don't split by anything in this dimension." period can be ommitted here.
```

```{r}

weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.5) +
  facet_grid(col = vars(name)) # newer, more explicit syntax. "Make a grid of panels where the columns come from the name variable."
``` 


Look at sth else  

```{r}
weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) #se=FALSE means not showing confident level, se=true by default
  facet_grid(. ~ name)
```
  
make a plot of central park tmax vs tmin only, and convert temperatures from celcius to farenheit.  

```{r}
weather_df |> 
  filter(name == "CentralPark_NY") |> 
  mutate(
    tmin = tmin*(9/5)+32,
    tmax = tmax*(9/5)+32
  ) |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

what's a hex plot  

```{r}
library(hexbin)
```
  
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_hex() #2d histogram with hex boxes
```


## Univariate plots  

```{r}
weather_df |> 
  ggplot(aes(x = tmax)) + 
  geom_histogram()
```
```{r}
weather_df |> 
  ggplot(aes(x = tmax, color = name)) + 
  geom_histogram(position = "dodge") + 
  facet_grid(col = vars(name))
```

Density plots are great!  

```{r}
weather_df |> 
  ggplot(aes(x = tmax, fill = name)) + 
  geom_density(alpha = .3)
``` 

Box plots  

```{r}
weather_df |> 
  ggplot(aes(x = name, y = tmax)) + 
  geom_boxplot()
```
  
Violin plot  

```{r}
weather_df |> 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin()
```

  
Ridge plots  

```{r}
weather_df |> 
  ggplot(aes(x = tmax, y =name)) + 
  geom_density_ridges() # for many categories
```
  

## save some of my plots  

```{r}
ggp_weather <- 
  weather_df |> 
    ggplot(aes(x = date, y = tmax, color = name)) + 
    geom_point(aes(size = prcp), alpha= 0.5) + 
    facet_grid(col = vars(name))

ggsave("images/ggp_weather.pdf", ggp_weather)
```

```{r fig.width = 12, fig.height = 12} 
# "fig.width = 12, fig.height = 12" in r chunk to set and adjust figure settings 

weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

